---
Name: nextgenimages
After: "#assetsimage"
---
SilverStripe\Assets\Image:
  extensions:
    - 'WebbuildersGroup\NextGenImages\Extensions\ImageExtension'

SilverStripe\Assets\Storage\DBFile:
  extensions:
    - 'WebbuildersGroup\NextGenImages\Extensions\ImageExtension'
